language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - nightly

notifications:
  email: false

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("HSL"); Pkg.test("HSL"; coverage=true)'
 # - julia --check-bounds=yes -e 'using Pkg; Pkg.add("BinDeps"); Pkg.add("Compat"); Pkg.build("BinDeps"); using BinDeps; BinDeps.debug("HSL")'
