language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - 1.0
    - nightly

branches:
  only:
    - master

notifications:
  email: false

script:
  - julia -e 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/HSL.jl.git")'
  - true

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("HSL")); include(joinpath("docs", "make.jl"))'
