language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - julia -e 'Pkg.add("Documenter")'

script:
  - julia -e 'cd(Pkg.dir("HSL")); include(joinpath("docs", "make.jl"))'
